// eslint-disable-next-line import/no-anonymous-default-export
export default[
    {
        id: 1,
        image: require('./images/product-images/store-lamp1.png'),
        description1: 'Tripod Lamp',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '1050.00',
        button: 'Add to bag',
    },
    {
        id: 2,
        image: require('./images/product-images/store-lamp2.png'),
        description1: 'Black ceramic table lamp',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '200.00',
        button: 'Add to bag',
    },
    {
        id: 3,
        image: require('./images/product-images/store-lamp4.png'),
        description1: 'Floor lamp with wooden base design',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '1200.00',
        button: 'Add to bag',
    },
    {
        id: 4,
        image: require('./images/product-images/store-lamp3.png'),
        description1: 'Black floor lamp',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '250.00',
        button: 'Add to bag',
    },
    {
        id: 5,
        image: require('./images/product-images/store-lamp5.png'),
        description1: 'Bronze and black table lamp',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '400.00',
        button: 'Add to bag',
    },
    {
        id: 6,
        image: require('./images/product-images/store-lamp6.png'),
        description1: 'Gold and cream table lamp',
        Item: 'Vase',
        color: 'Yellow',
        description2:'Mill Oil is an innovative oil filled radiator with the most modern technology.If you are looking for something that can make your interior look awesome, and at the same time.',
        price: '760.00',
        button: 'Add to bag',
    },
]